@startuml name
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(person, "Пользователь")
Container_Boundary(bound_dwh, "DWH"){
    ContainerDb(postgres_dwh, "DWH хранилище", "Microsoft Sql 2008")
}

Container_Boundary(bi_system, "BI System"){
    Container(dwh_power_builder, "Интерфейс(*WEB)", "Power Builder", "")
    Container(dwh_power_bi, "Интерфейс(*WEB)", "Power BI", "")
}
Container_Boundary(bound_finteh, "Фин тех сервисы"){
    Container(fin_teh_1, "Финтех сервис 1", "Go")
    Container(fin_teh_2, "Финтех сервис 2", "Java")
}
Container_Boundary(bound_ai, "ИИ сервисы"){
    Container(ai_1,"ИИ сервис 1", Python)
    Container(ai_12,"ИИ сервис 1", Python)
}
ContainerQueue(broker, "Брокер сообщений", "Apache Camel")

Rel_D(person,bound_dwh,"Мед данные, снимки")
Rel_R(bound_dwh,bi_system, "Даннные")
BiRel_U(broker,bound_dwh,"")
BiRel_L(broker,bound_ai, "Мед данные")
BiRel_R(broker,bound_finteh, "Фин данные")
@enduml
